name: "Resize image"
description: "Resize a image using Libvips, with Lanczos kernel algorithm"
author: "Yeray David Rodriguez"
inputs:
  dvc_diff:
    description: "Result of the DVC DIFF execution"
    required: true
  width:
    description: "Maximum destination image width"
    required: true
  height:
    description: "Maximum destination image height"
    required: true
outputs:
  result:
    description: "The modified input structure"
runs:
  using: "docker"
  image: "Dockerfile"

