name: "Modify Image File Format"
description: "Modify the file format of a image using Libvips"
author: "Yeray David Rodriguez"
inputs:
  job_state:
    description: "JSON structure containing 'icc profile modify output' attribute with files to modify"
    required: true
  format:
    description: "File format for destination images (i.e. 'jpg' ). Will be also used as extension."
    required: true
outputs:
  result:
    description: "The modified input structure"
runs:
  using: "docker"
  image: "Dockerfile"

