name: Change image profile using GitHub Action

on:
  push:
    branches: [ main, issue-* ]

jobs:
  change-profile:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}

    steps:
      - uses: actions/checkout@v2

      - name: Setup DVC
        uses: iterative/setup-dvc@v1

      - name: Pull images from remote storage
        env:
          AZURE_STORAGE_ACCOUNT: ${{ secrets.AZURE_STORAGE_ACCOUNT }}
          AZURE_STORAGE_SAS_TOKEN: ${{ secrets.AZURE_STORAGE_SAS_TOKEN }}
        run: dvc pull --remote azure      

      - name: Generate Base image
        uses: ./.github/actions/change-image-profile
        with:
          source_images: ${{ github.workspace }}/data/000002/32/000002-32.600.2.tif, ${{ github.workspace }}/data/000002/32/000002-32.600.3.tif 
          destination_images: ${{ github.workspace }}/data/000002/42/000002-32.600.2.tif, ${{ github.workspace }}/data/000002/42/000002-32.600.3.tif 
          profile: sRGB

      - name: Archive resized image
        uses: actions/upload-artifact@v2
        if: ${{ !env.ACT }}
        with:
          name: sample-resized-image
          path: test-reduced.tif
  