name: Commit files and push commit using GitHub Action

on:
  push:
    branches: [ main, issue-* ]

jobs:
  auto-commit-push:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}

    steps:
      - uses: actions/checkout@v2

      - name: Commit files
        uses: ./.github/actions/auto-commit-push
        env:
          FILENAMES: '{"added": [], "modified": [], "renamed": [], "not in cache": [], "resize input": [], "move to base folder output": ["data/test/landscape.jpg"]}'
          MESSAGE: 'This is a test'
          BRANCH: 'test-branch'
