name: Gold Drawings Processing Using Nautilus Librarian

on:
  pull_request:
    branches: [ main, issue-* ]

jobs:
  process-gold-images:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0 # To fetch all history for all branches and tags. Needed for git diff.
          submodules: 'true'

      - name: Setup Python
        uses: actions/setup-python@v2.3.1
        with:
          python-version: '3.9'

      - name: Setup Poetry
        run: pip3 install poetry poetry-dynamic-versioning

      - name: Install Librarian with Poetry
        run: |
          cd librarian
          poetry --version
          poetry install
          poetry version --short
          poetry build
          pip install --user "${{ github.workspace }}/librarian/dist/nautilus_librarian-$(poetry version --short)-py3-none-any.whl"
          nautilus-librarian --help

      - name: Run librarian gold image processing command
          nautilus_librarian gold-image-processing
