name: Gold Drawings Processing

on:
  pull_request:
    branches: [ main, issue-* ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0 # To fetch all history for all branches and tags. Needed for git diff.

      # debug info to run locally with 'act'. It shows secrets!!
      #- name: Dump context
      #  uses: crazy-max/ghaction-dump-context@v1

      - name: Debug env vars
        shell: bash
        run: |
          # https://docs.github.com/en/actions/learn-github-actions/environment-variables#default-environment-variables
          echo -e "GITHUB_SHA: $GITHUB_SHA\n"
          echo -e "GITHUB_REF: $GITHUB_REF\n"
          echo -e "GITHUB_HEAD_REF: $GITHUB_HEAD_REF\n"
          echo -e "GITHUB_BASE_REF: $GITHUB_BASE_REF\n"
          echo -e "GITHUB_EVENT_NAME: $GITHUB_EVENT_NAME\n"
          echo -e "GITHUB_EVENT_PATH: $GITHUB_EVENT_PATH\n" 
          #cat $GITHUB_EVENT_PATH

      - name: Git diff
        run: |
          #git remote -v
          #git status
          git show-ref
          #git log --oneline
          #echo "git diff origin/${{ github.base_ref }} HEAD"
          git diff origin/${{ github.base_ref }} HEAD

      - name: DVC diff
        id: dvc-diff
        uses: ./.github/actions/dvc-diff
        env:
          DVC_REPO_DIR: ${{ github.workspace }}
          PREVIOUS_REF: "origin/${{ github.base_ref }}"
          CURRENT_REF: HEAD

      - name: Debug diff ouput
        run: |
          echo "The diff output is: ${{ steps.dvc-diff.outputs.diff }}"

      - name: Validate filenames
        if: steps.dvc-diff.outputs.diff != '{}'
        uses: ./.github/actions/validate-filenames
        with:
          filenames: ${{ steps.dvc-diff.outputs.diff }}