name: Resize image using GitHub Action

on:
  push:
    branches: [ main, issue-* ]

jobs:
  resize:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}

    steps:
      - uses: actions/checkout@v2

      - name: Setup DVC
        uses: iterative/setup-dvc@v1

      - name: Pull images from remote storage
        env:
          AZURE_STORAGE_ACCOUNT: nautiluscyberneering
          AZURE_STORAGE_SAS_TOKEN: '?sv=2020-08-04&ss=bfqt&srt=sco&sp=rwdlacuptfx&se=2022-03-31T19:18:40Z&st=2021-10-07T11:18:40Z&spr=https&sig=R7akkWtRpdzckb5MfMlZ0GF6ogDlIZTZ1R%2BN9ph437Y%3D'
        run: dvc pull --remote azure      

      - name: Generate Base image
        uses: ./.github/actions/resize-image
        with:
          source_images: ${{ github.workspace }}/data/000002/32/000002-32.600.2.tif, ${{ github.workspace }}/data/000002/32/000002-32.600.3.tif 
          destination_images: ${{ github.workspace }}/data/000002/42/000002-32.600.2.tif, ${{ github.workspace }}/data/000002/42/000002-32.600.3.tif 
          width: 320
          height: 200

      - name: Archive resized image
        uses: actions/upload-artifact@v2
        if: ${{ !env.ACT }}
        with:
          name: sample-resized-image
          path: test-reduced.tif
  