name: Test Librarian integration using Docker

on:
  pull_request:
    branches: [ main, issue-* ]

jobs:
  test-librarian-submodule:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:  
          submodules: 'true'

      - name: Build docker image
        run: |
          cd librarian && ./bin/docker/build.sh

      - name: Invoke "help" on Librarian
        run: |
          cd librarian && ./bin/docker/run.sh --help
