name: Test librarian submodule

on:
  pull_request:
    branches: [ main, issue-* ]

jobs:
  process-gold-images:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:  
          submodules: 'true'

      - name: Build docker image
        run: |
          cd librarian
          ./bin/build.sh

      - name: Invoke "process" command on librarian
        run: |
          docker run --rm librarian process
