name: Test Librarian integration using Poetry

on:
  push:
    branches: [ main, develop, issue-* ]

jobs:
  build:
    name: Test
    runs-on: ubuntu-latest
    steps:
    
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2.3.1
        with:
          python-version: '3.9'

      - name: Setup Poetry
        run: pip3 install poetry

      - name: Check Poetry
        run: poetry --version

      - name: Config Poetry for Cache
        if: ${{ !env.ACT }}
        run: poetry config virtualenvs.in-project true

      - name: Cache the virtualenv
        if: ${{ !env.ACT }}
        uses: actions/cache@v2.1.6
        with:
          path: ./.venv
          key: ${{ runner.os }}-venv-v0-${{ hashFiles('**/poetry.lock') }}

      - name: Install via Poetry
        run: |
          cd librarian
          poetry install
          poetry build
          pip install --user "${{ github.workspace }}/librarian/dist/nautilus_librarian-0.1.0-py3-none-any.whl"

      - name: Invoke "help" on Librarian
        run: |
          nautilus-librarian --help