name: Change image file format using GitHub Action

on:
  push:
    branches: [ main, issue-* ]

jobs:
  change-image-format:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}

    steps:
      - uses: actions/checkout@v2

      - name: Setup DVC
        uses: iterative/setup-dvc@v1

      - name: Pull images from remote storage
        env:
          AZURE_STORAGE_ACCOUNT: ${{ secrets.AZURE_STORAGE_ACCOUNT }}
          AZURE_STORAGE_SAS_TOKEN: ${{ secrets.AZURE_STORAGE_SAS_TOKEN }}
        run: dvc pull --remote azure      

      - name: Change image format
        uses: ./.github/actions/change-image-file-format
        id: change-format
        with:
          job_state: '{"added": [], "modified": [], "renamed": [], "not in cache": [], "resize input": [], "icc profile modify output": ["/github/workspace/data/000002/32/000002-32.600.2.tif"]}'
          format: jpg

      - name: Check structure after image file format change step
        run: echo "${{ steps.change-format.outputs.result }}"
