name: Copy image to base images folder using GitHub Action

on:
  push:
    branches: [ main, issue-* ]

jobs:
  copy-image-to-base-folder:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}

    steps:
      - uses: actions/checkout@v2

      - name: Setup DVC
        uses: iterative/setup-dvc@v1

      - name: Pull images from remote storage
        env:
          AZURE_STORAGE_ACCOUNT: ${{ secrets.AZURE_STORAGE_ACCOUNT }}
          AZURE_STORAGE_SAS_TOKEN: ${{ secrets.AZURE_STORAGE_SAS_TOKEN }}
        run: dvc pull --remote azure      

      - name: Copy image to base
        uses: ./.github/actions/copy-to-base-folder
        id: copy-to-base
        with:
          job_state: '{"added": [], "modified": [], "renamed": [], "not in cache": [], "resize input": [], "file format change output": ["data/000002/32/000002-32.600.2.tif"]}'
          format: jpg

      - name: Check structure after image copy step
        run: echo "${{ steps.copy-to-base.outputs.result }}"