name: Validate image size using GitHub Action

on:
  push:
    branches: [ main, issue-* ]

jobs:
  validate-size:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}

    steps:
      - uses: actions/checkout@v2

      - name: Setup DVC
        uses: iterative/setup-dvc@v1

      - name: Pull images from remote storage
        env:
          AZURE_STORAGE_ACCOUNT: ${{ secrets.AZURE_STORAGE_ACCOUNT }}
          AZURE_STORAGE_SAS_TOKEN: ${{ secrets.AZURE_STORAGE_SAS_TOKEN }}
        run: dvc pull --remote azure   

      - name: Validate Base image
        uses: ./.github/actions/validate-image-size
        with:
          DVC_DIFF: '{"added": [{"path": "data/000002/32/000002-32.600.2.tif"}], "modified": [], "renamed": [], "not in cache": []}'
          min_size: 320
          max_size: 340000

      - name: Final step
        run: echo "Workflow finished"  
